name: "Upgrade application"
on:
  schedule:
    - cron: "0 8 * * MON"
  workflow_dispatch:

jobs:
  upgrade-dependencies:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:17
        ports: ["5432:5432"]
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        env:
          POSTGRES_PASSWORD: postgres
    env:
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: postgres
      DATABASE_HOST: localhost

    steps:
      - name: Upgrade instance dependencies
        uses: openpoke/decidim-shared-actions/upgrade_instance@main
        with:
          ruby-version: "3.2.8"
