name: "Upgrade application"
on:
  schedule:
    - cron: "0 8 * * MON"
  workflow_dispatch:

jobs:
  upgrade-dependencies:
    runs-on: ubuntu-latest

    steps:
      - name: Upgrade instance dependencies
        uses: openpoke/decidim-shared-actions/upgrade_instance@main
        with:
          ruby-version: "3.2.8"
